version: "3"
services:
  python312:
    container_name: "python312"
    # restart: no
    build:
      dockerfile: Dockerfile
    working_dir: "/root/"
    tty: true
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - /Users/seijun/Documents/dev/:/root/workspace
  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     - "dbdata:/var/lib/postgresql/data"
