version: "3"
services:
  python310:
    container_name: "python310"
    # restart: no
    build:
      dockerfile: Dockerfile
    working_dir: "/root/"
    tty: true
    # entrypoint: >
    #   jupyter-lab
    #   --allow-root
    #   --ip=0.0.0.0
    #   --port=8888
    #   --no-browser
    #   --NotebookApp.token=''
    #   --notebook-dir=/workspace
    # expose:
    #   - "8888"
    ports:
      - "8888:8888"
    volumes:
      - /Users/seijun/Documents/dev/:/root/workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     - "dbdata:/var/lib/postgresql/data"
